Update Ubuntu distribution to 22.04 and do not build Rust
21.04 is not supported anymore which results in apt-get errors:

 E: The repository 'http://archive.ubuntu.com/ubuntu hirsute Release' does not have a Release file.

Therefore upgrade to 22.04. At the same time, do not pre-build the Rust
stuff because it just fails to build and I don't understand why:

 error: failed to fetch https://github.com/rust-lang/crates.io-index  Caused by:
   error inflating zlib stream; class=Zlib (5)

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>